server:
  port: 9090
cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    stack:
      auto: false
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
livy:
  url: http://localhost:8157